services:
  mariadb:
    # https://docs.hetzner.com/konsoleh/general/faq/softwareupdate2024/
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    env_file: .docker/mariadb.env
    ports:
      - "3306:3306"
    volumes:
      - .mariadb_data:/var/lib/mysql

  webapp:
    build: .
    container_name: community-bulletin-board
    restart: always
    env_file: .docker/webapp.env
    ports:
      - "8000:8000"

volumes:
  .mariadb_data:
